# 00_PyTorch Fundamentals

In [63]:
# Install torch module
%pip install torch

import torch
print(torch.__version__)

Note: you may need to restart the kernel to use updated packages.
2.5.1+cpu


In [64]:
import torch

## Intro to Tensors

In [65]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [66]:
scalar.ndim

0

In [67]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [68]:
vector.ndim

1

In [69]:
#MATRIX 
MATRIX = torch.tensor([[[[1, 1, 1],
                         [2, 2, 2],
                         [3, 3, 3],
                         [4, 4, 4]]],
                         [[[1, 1, 2],
                         [2, 2, 2],
                         [3, 3, 3],
                         [4, 4, 4]]]])
MATRIX

tensor([[[[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3],
          [4, 4, 4]]],


        [[[1, 1, 2],
          [2, 2, 2],
          [3, 3, 3],
          [4, 4, 4]]]])

In [70]:
MATRIX.ndim # dimensi adalah banyaknya square brackets di dalam tensor

4

In [71]:
MATRIX.shape # shape adalah urutan banyaknya elemen pada sqb terluar ke terdalam

torch.Size([2, 1, 4, 3])

### Random Tensors

In [72]:
random_tensor = torch.rand(10, 10)
random_tensor

tensor([[0.5994, 0.3052, 0.3714, 0.9819, 0.0724, 0.6950, 0.3543, 0.0812, 0.8942,
         0.1810],
        [0.7338, 0.6257, 0.7853, 0.8815, 0.3748, 0.8950, 0.1922, 0.4324, 0.6464,
         0.9493],
        [0.5165, 0.2511, 0.0022, 0.7221, 0.5870, 0.4305, 0.0718, 0.9251, 0.5822,
         0.6016],
        [0.1211, 0.6641, 0.3463, 0.3348, 0.8664, 0.3790, 0.5047, 0.8947, 0.8157,
         0.0569],
        [0.9341, 0.1077, 0.3113, 0.7658, 0.9976, 0.7746, 0.5179, 0.0090, 0.2684,
         0.8196],
        [0.1812, 0.0665, 0.8656, 0.2247, 0.7619, 0.0680, 0.8140, 0.7931, 0.5796,
         0.5045],
        [0.1798, 0.9075, 0.7687, 0.9634, 0.9209, 0.6555, 0.3367, 0.7524, 0.5143,
         0.8734],
        [0.9600, 0.7900, 0.8426, 0.6395, 0.7197, 0.6930, 0.4774, 0.1477, 0.3075,
         0.2790],
        [0.2853, 0.6436, 0.1024, 0.0858, 0.6033, 0.4676, 0.9305, 0.8978, 0.4810,
         0.8785],
        [0.3427, 0.7968, 0.8591, 0.3116, 0.4716, 0.1344, 0.5477, 0.3453, 0.9326,
         0.7958]])

In [73]:
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channel
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones tensor

In [74]:
ones = torch.ones(3, 4)
ones * torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Tensor Datatype

**Note** : 3 error yang akan sering ditemui ketika belajar PyTorch & Deep Learning
1. tipe data tensor yang salah
2. bentuk tensor yang tidak benar
3. tensors not in the right device


In [75]:
# float32 tensors
float_32_tensor =  torch.tensor([3.0, 6.0, 4.0], 
                                dtype=None, # default is torch.float32 
                                device=None, # what device the tensor is on
                                requires_grad=False) # whether or not to track gradients with this tensor
float_32_tensor.dtype

torch.float32

In [76]:
tensor_64_int = torch.tensor([3, 6, 4], dtype=torch.int64)

multiply = float_32_tensor * tensor_64_int
multiply

tensor([ 9., 36., 16.])

- tensor dengan tipe data yang berbeda bisa dioperasikan, namun hasilnya akan mengikuti tipe data yang lebih tinggi
- untuk mengetahui type data tensor, kita bisa menggunakan `.dtype`
- untuk mengetahui device apa yang digunakan untuk mengoperasikan tensor, kita bisa menggunakana `.device`
- untuk mengetahui shape dari tensor, kita bisa menggunakan `.shape`



In [77]:
tensor_64_int.device

device(type='cpu')

In [78]:
rand_tensor = torch.rand(5, 5);
print(rand_tensor)
print(f"The shape of the tensor is : {rand_tensor.shape}")
print(f"The dtype of the tensor is a : {rand_tensor.dtype}")
print(f"The device the tensor executed is on : {rand_tensor.device}")


tensor([[0.1152, 0.8774, 0.3883, 0.2855, 0.5464],
        [0.5504, 0.6045, 0.8958, 0.6380, 0.2573],
        [0.7259, 0.2012, 0.4409, 0.5893, 0.5924],
        [0.6521, 0.3591, 0.3563, 0.2073, 0.4995],
        [0.7108, 0.8589, 0.1440, 0.1234, 0.7630]])
The shape of the tensor is : torch.Size([5, 5])
The dtype of the tensor is a : torch.float32
The device the tensor executed is on : cpu


### Tensor Manipulation

Tensor operations, include :
1. addition
2. subtraction
3. multiplication (elemen wise)
4. division 
5. matrix multiplication

In [79]:
# create a tensor
num_tensor = torch.rand(3, 3)
num_tensor

tensor([[0.6898, 0.7529, 0.5268],
        [0.5890, 0.4786, 0.4908],
        [0.7032, 0.8017, 0.4001]])

In [80]:
# membuat tensor berada dalam rentang 0-9
num_tensor *= 10
num_tensor

tensor([[6.8982, 7.5286, 5.2678],
        [5.8896, 4.7856, 4.9081],
        [7.0319, 8.0170, 4.0012]])

In [81]:

# menambahkan angka ke dalam tensor
num_tensor + 1

tensor([[7.8982, 8.5286, 6.2678],
        [6.8896, 5.7856, 5.9081],
        [8.0319, 9.0170, 5.0012]])

In [82]:
# menambahkan tensor suatu bilangan
num_tensor + 1

tensor([[7.8982, 8.5286, 6.2678],
        [6.8896, 5.7856, 5.9081],
        [8.0319, 9.0170, 5.0012]])

In [83]:
# mengurangi tensor suatu bilangan
num_tensor - 1

tensor([[5.8982, 6.5286, 4.2678],
        [4.8896, 3.7856, 3.9081],
        [6.0319, 7.0170, 3.0012]])

#### Tensor Multiplication
1. Element-wise mul
2. Matrix mul

In [84]:
int_tensor = (torch.rand(3, 3)*10).to(torch.int64)
int_tensor

tensor([[6, 9, 0],
        [8, 9, 0],
        [0, 9, 6]])

In [85]:
# Element-wise multiplication
int_tensor * 10


tensor([[60, 90,  0],
        [80, 90,  0],
        [ 0, 90, 60]])

Menggunakan looping manual tanpa bantuan PyTorch


In [86]:
%%time
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([2, 3, 4])
total = 0

for i in range(len(tensor1)):
    total += tensor1[i] * tensor2[i]
print(total)

tensor(20)
CPU times: total: 0 ns
Wall time: 999 μs


Menggunakan framework PyTorch


In [87]:
%%time
print(torch.matmul(tensor1, tensor2))

tensor(20)
CPU times: total: 0 ns
Wall time: 1 ms


tensor_A = torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])
tensor_B = torch.tensor([[7, 10],
                          [8, 11],
                          [9, 12]])
print(f"shape of tensor A is {tensor_A.shape} and shape of tensor B is {tensor_B.shape}")

In [88]:
# matrix multiplication     
AxB = torch.mm(tensor_A, tensor_B.T)
AxB, AxB.shape

NameError: name 'tensor_B' is not defined

#### Tensor Aggregation 
Finding min, max, mean, sum, etc

In [55]:
X = torch.arange(0, 100, 10)
X = X.to(torch.float32)
X

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [56]:
torch.min(X), torch.max(X), torch.mean(X)

(tensor(0.), tensor(90.), tensor(45.))

In [58]:
# find the index of the max value
torch.argmax(X), torch.argmin(X)

(tensor(9), tensor(0))

### Reshaping, stacking, squeezing, and unsqueezing

* Reshaping - reshape an input tensor to a defined shape
* View 
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimension from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input dimension permuted(swapped) in a certain way

In [30]:
# Reshape
tensor_A = torch.arange(1,13, 1);
tensor_A, tensor_A.size()

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [31]:
tensor_A.reshape(3, 4), tensor_A.reshape(2, 6)


(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]))

In [42]:
# Add extra dimension
A_reshaped = tensor_A.reshape(3, 4)
A_reshaped, A_reshaped.shape, A_reshaped.dim()

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]),
 2)

#### View


In [43]:
X = torch.arange(1, 10, 1)
Z = X.view(1, 9)
Z, Z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [45]:
Z[:, 0] = 5
Z, X

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

#### Squeeze and Unsqueeze

In [49]:
# torch.squeeze removes all single dimension from a target tensor
# membuat tensor
X = torch.arange(1, 10, 1)
X_reshaped = X.reshape(1, 9)

# melihat dimensi
print(f"ini adalah tensor awal : {X_reshaped}")
print(f"ukurannya adalah {X_reshaped.shape}")

# menampilkan dimensi akhir
X_squeezed = X_reshaped.squeeze()
print(f"ini adalah tensor hasil squeezing {X_squeezed}")
print(f"ukurannya adalah {X_squeezed.shape}")

ini adalah tensor awal : tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
ukurannya adalah torch.Size([1, 9])
ini adalah tensor hasil squeezing tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
ukurannya adalah torch.Size([9])


In [55]:
# torch.unsquezee() - add a single dimension to a target tensor

# melihat dimensi
print(f"ini adalah tensor awal : {X_squeezed}")
print(f"ukurannya adalah : {X_squeezed.shape}")

X_unsqueezed = X_squeezed.unsqueeze(0)
print(f"ini adalah tensor hasil unsqueeze {X_unsqueezed}")
print(f"ukurannya adalah : {X_unsqueezed.shape}")


ini adalah tensor awal : tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
ukurannya adalah : torch.Size([9])
ini adalah tensor hasil unsqueeze tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
ukurannya adalah : torch.Size([1, 9])


#### Tensor Permutation
Fungsi utama : mengubah urutan dimensi yang dimiliki tensor

**note** : permutasi tensor adalah view dari tensor asal, artinya mengubah tensor hasil permutasi juga mengubah tensor asal karena mereka berbagi alamat memori yang sama

In [58]:
x_original = torch.rand(size=(224, 224, 3)) # height, width, color channel
print(f"ini adalah tensor awal {x_original}")
print(f"bentuknya adalah : {x_original.shape}")

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)
print(f"ini adalah tensor permuted {x_permuted}")
print(f"bentuknya adalah : {x_permuted.shape}")


ini adalah tensor awal tensor([[[0.6629, 0.6527, 0.0719],
         [0.9382, 0.2608, 0.4452],
         [0.5099, 0.7344, 0.2992],
         ...,
         [0.0872, 0.2946, 0.0922],
         [0.9883, 0.1089, 0.5583],
         [0.0963, 0.4558, 0.6091]],

        [[0.5947, 0.6384, 0.3215],
         [0.7610, 0.7105, 0.8761],
         [0.6772, 0.6460, 0.0734],
         ...,
         [0.7021, 0.9431, 0.1790],
         [0.8540, 0.9552, 0.0806],
         [0.9255, 0.7137, 0.6329]],

        [[0.2093, 0.5691, 0.3229],
         [0.5280, 0.9966, 0.1848],
         [0.7332, 0.1532, 0.5451],
         ...,
         [0.9294, 0.6063, 0.2123],
         [0.1182, 0.8693, 0.0943],
         [0.4359, 0.8949, 0.1929]],

        ...,

        [[0.2213, 0.4515, 0.5196],
         [0.1736, 0.1795, 0.0225],
         [0.1995, 0.1366, 0.6316],
         ...,
         [0.7848, 0.0190, 0.0388],
         [0.7667, 0.0359, 0.0088],
         [0.4562, 0.8717, 0.9169]],

        [[0.4846, 0.9629, 0.9172],
         [0.8490, 0.7729

In [60]:
# bukti bahwa keduanya berbagi alamat memori yang sama
x_original[0, 0, 0] = 12345
x_original[0, 0, 0], x_permuted[0, 0, 0]    

(tensor(12345.), tensor(12345.))

### Indexing and Slicing


In [89]:
# creating a tensor
x = torch.tensor([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]])
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [90]:
x[:, :, 2] # all rows, all columns, index 2

tensor([[3, 6, 9]])

In [91]:
x[:, 2, 1]

tensor([8])

In [92]:
x[:, 1, 2]

tensor([6])

### Tensor and NumPy library



In [100]:
# numpy array to tensor 
import torch
import numpy as np

array = np.arange(1.0, 8.0, 1) # dtype : float64
array = array.astype(np.float32) 
tensor = torch.from_numpy(array) 
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [102]:
np_array = tensor.numpy()
np_array, np_array.dtype

(array([1., 2., 3., 4., 5., 6., 7.], dtype=float32), dtype('float32'))